### ISSUE TITLE
Need a new release with prometheus v2.8.0 or later

### ISSUE THREAD

**Issue by llamahunter** [coreos/kube-prometheus#154]
There are bugs with remote_write implementation in the pre v2.8.0 versions of prometheus.  Need a release of kube-prometheus with that 2.8.0 or later.

**Comment by brancz** [comment]
You should always be able to use `master`, but we're going to cut a 0.2 branch within a couple of weeks probably.

**Comment by janlau1111** [comment]
Hi, are there any updates regarding a new release?

**Comment by brancz** [comment]
I believe @LiliC mentioned we're soon (as in within the next couple of days going to get to this)

**Comment by brancz** [comment]
but again, the "support" has no difference, master is just as supported or not as a release branch is

**Comment by LiliC** [comment]
https://github.com/coreos/kube-prometheus/releases/tag/v0.2.0 Done :)

**Comment by jascott1** [comment]
Master is not a viable option for us. Is there anyway we can get a point release for v0.2.0? Grafana deployment's api version update was missed and it breaks deployment on k8s 1.16.

**Comment by brancz** [comment]
can you explain why master is then not an option for you?

**Comment by jascott1** [comment]
We are currently using a SHA from master which will suffice. 'latest' from master has the same problems as using a 'latest' container. You need known revisions to work with complicated distributed systems or updated and non-updated deployments will differ and cause confusion. 

I encourage the maintainers to have some release cadence. I recently came here looking for Prometheus thats compatible with k8s 1.16, so I grabbed latest release which doesn't install successfully. I then spend time troubleshooting and arrive at a missed api version update of the Grafana deployment, check that it is fixed in master and find  a SHA that can be used. Today every user looking for 1.16 compatibility will follow a similar process because this project believes in 'just use master' instead of point releases. Something to consider, thanks!

**Comment by LiliC** [comment]
Since release was cut, we can close this now.
