### ISSUE TITLE
AlertManager received the alert five minutes later than prometheus. Have you encountered it?

### ISSUE THREAD

**Issue by yq513** [coreos/kube-prometheus#354]
AlertManager is five minutes late for prometheus. Have you encountered it?

I deployed AlertManager and prometheus in kubernetes 1.16.2 and found that AlertManager received the alert five minutes later than prometheus. Is this a bug?
![image](https://user-images.githubusercontent.com/39945790/71538421-894a3900-2965-11ea-8881-3c13ec992b4f.png)
![image](https://user-images.githubusercontent.com/39945790/71538423-9a934580-2965-11ea-86e6-105f75e70747.png)

kubernetes 1.16.2
AlertManager 0.20.0
prometheus 2.14.1

**Comment by simonpasquier** [comment]
This is because of the `for` parameter which is set to 5 minutes: the alert is active as soon as the expression returns something but Prometheus waits for the alert to be active for 5 minutes before sending it. If you want the alert to be sent immediately, `for` can be omitted but it can led to flapping alerts.
