### ISSUE TITLE
alertmanager/alertmanager-main's config-volume is called cm/alertmanager-alertmanager-main

### ISSUE THREAD

**Issue by urzds** [coreos/kube-prometheus#43]
After running `deploy`:

```
Volumes:
  config-volume:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       alertmanager-alertmanager-main
...
...: timeout expired waiting for volumes to attach/mount for pod "monitoring"/"alertmanager-alertmanager-main-0". list of unattached/unmounted volumes=[config-volume]
```

This happens, because `alertmanager/alertmanager-main` expects its config map to be named `cm/alertmanager-alertmanager-main`, while it is actually created as `cm/alertmanager-main` by `kube-prometheus/.../deploy`.

Might be implicitly fixed by #33, even though it is already broken right now and the behavioural change was not introduced by prometheus-operator-0.5.

**Comment by brancz** [comment]
This is a change introduced by the v0.3.0 release of the operator, which is why current master of this repository is pinned to the v0.2.x release series. Yes indeed #33 is upgrading to the latest Operator version and fixes all the incompatibilities and also upgrades other components such as kube-state-metrics. I'm expecting #33 to land soon, but will probably have to wait for the v0.5.1 release of the Operator.

**Comment by urzds** [comment]
Maybe my setup was confused from an earlier installation of the Prometheus operator 0.5. After running `teardown` several times, deleting stuff manually and especially deleting the `monitoring` namespace manually, I finally have several instances of the alertmanager running. Thus closing this as invalid.
