### ISSUE TITLE
Custom services datasource

### ISSUE THREAD

**Issue by tsloughter** [coreos/kube-prometheus#44]
When adding a custom service to monitor the metrics of my apps, like running `hack/example-service-monitoring/deploy`, I then had to manually add the datasource `http://prometheus.default.svc:9090` in the Grafana ui before I could see those metrics.

Is this a required step or did I do something else wrong? I could not tell from the readme one way or the other.

**Comment by urzds** [comment]
I confirm this issue: My own application (not the example) shows up in Grafana, but only displays a graph for `Memory Usage`. `CPU Usage` and `Network I/O` are displayed with `No datapoints`.

**Comment by brancz** [comment]
These are two distinct problems you are describing.

@tsloughter This is one of the things we want to take care of with a [Grafana integration](https://github.com/coreos/prometheus-operator/issues/115) in the Prometheus Operator. For the time being you should be able to create another [datasource](https://github.com/coreos/kube-prometheus/blob/3a38e173f9a09f27d3a5a59c0cbd59ff8c671ba8/manifests/grafana/grafana-cm.yaml#L3006) and select the appropriate one for each dashboard. An alternative would be to have a completely separate Grafana instance for each Prometheus cluster.

I would not recommend using the `Service` called `prometheus` as a grafana datasource as this `Service` acts as a governing `Service` for the `StatefulSet`s of Prometheus. That means that when you create multiple Prometheus clusters in the same namespace they will all be part of that one `Service`, which means you will get arbitrary query results as you don't know which cluster you are actually requesting.

@urzds Unfortunately there have been some breaking changes in latest cadvisor/kubelet metrics which are causing this, these will be fixed with #33.

**Comment by tsloughter** [comment]
@brancz thanks. But if not `prometheus` what service should be used as the datasource in grafana?

I guess I don't understand why I need multiple prometheus clusters at all, but that may be my limited knowledge of prometheus.

**Comment by brancz** [comment]
The example service Prometheus cluster is currently not reflected in Grafana as of this repository today. If you wanted to do that for the example service included in this repository you need to create another datasource for Grafana with `http://prometheus-frontend.default.svc:9090` as the URL (because of [this Service](https://github.com/coreos/kube-prometheus/blob/3a38e173f9a09f27d3a5a59c0cbd59ff8c671ba8/manifests/examples/example-app/prometheus-frontend-svc.yaml)), assuming it was deployed in the `default` namespace.

**Comment by brancz** [comment]
At least how the current Prometheus Operator works is that each instance in a Prometheus cluster represented by a `Prometheus` object runs with the same configuration. What that means is that each of these instances scrape the same targets and therefore collect the same data, they are running highly available. However, the question is what happens when a single Prometheus instance cannot scrape your entire infrastructure anymore? In that case you start sharding Prometheus instances, but this is where operating Prometheus becomes tricky and the Prometheus Operator is going to get, but we're not quite there. But as a first step it is always good to shard in a functional way, meaning that at least all the data you need for alerting is within one Prometheus instance (or HA instances), which when those functional shards become too large can then be sharded further. Read more about this in the [High Availability Documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/high-availability.md).

Essentially what this means for you is that you want to keep data related to each other in one Prometheus cluster, which is why we have one cluster for Kubernetes monitoring and then one or more clusters for monitoring the applications running on top of Kubernetes.

**Comment by tsloughter** [comment]
Thanks @brancz, I'll close this now.
