### ISSUE TITLE
Grafana dashboards slows down Jsonnet build considerably

### ISSUE THREAD

**Issue by bgagnon** [coreos/kube-prometheus#537]
**What happened?**
Using this package with [google/go-jsonnet](https://github.com/google/go-jsonnet), the build times are inflated considerably by the inclusion of Grafana dashboards.

**Did you expect to see some different?**
I did not expect ~90% of the build time to go into Grafana dashboard expansion. There must be some particularly inefficient expression somewhere in there...

**How to reproduce it (as minimally and precisely as possible)**:
This is the out-of-the-box build on a mid-2011 iMac 27":

```console
$ time ./build.sh 
+ set -o pipefail
++ pwd
+ PATH=/Users/benoit/Documents/ubisoft/kube-prometheus/tmp/bin:/Users/benoit/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
+ find manifests -type f '!' -name '*.yaml' -delete
+ rm -f kustomization

real	0m18.000s
user	0m31.897s
sys	0m1.152s
```

After removing all dashboards with this simple patch:

```diff
diff --git a/example.jsonnet b/example.jsonnet
index 54de1e3..36bd59c 100644
--- a/example.jsonnet
+++ b/example.jsonnet
@@ -11,6 +11,7 @@ local kp =
     _config+:: {
       namespace: 'monitoring',
     },
+    grafanaDashboards:: {},
   };
 
 { ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
```

The build time drops considerably:

```console
$ time ./build.sh 
+ set -o pipefail
++ pwd
+ PATH=/Users/benoit/Documents/ubisoft/kube-prometheus/tmp/bin:/Users/benoit/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
+ find manifests -type f '!' -name '*.yaml' -delete
+ rm -f kustomization

real	0m2.611s
user	0m3.739s
sys	0m0.645s
```

I tried following the rabbit hole down `kubernetes/kubernetes-mixin` and `brancz/kubernetes-grafana` but I figured I'd start by opening an issue here.

**Comment by brancz** [comment]
I dove into this a while ago as well, if I recall correctly the problem is the `std.manifestExJson` function which I believe for every dashboard has to resolve all references, which results in rebuilding kube-prometheus for every dashboard we have essentially. We could speed this up by separating out the dashboard generation to be independent from the rest, but it's quite convenient the way it is I feel.

**Comment by ghostsquad** [comment]
the above mentioned PR to `go-jsonnet` should significantly help this issue.

**Comment by Leo1003** [comment]
I came to here to remind people to check which jsonnet you are using, as the patch above only landed on [go-jsonnet](https://github.com/google/go-jsonnet).

If you are using [jsonnet](https://github.com/google/jsonnet) instead of [go-jsonnet](https://github.com/google/go-jsonnet) like me, you would still get the poor performance. :confused: 

```
$ # The C version
$ time jsonnet -J vendor -m manifests main.jsonnet
real    1m46.652s
user    1m46.063s
sys     0m0.896s

$ # The Go version
$ time gojsonnet -J vendor -m manifests main.jsonnet
real    0m3.364s
user    0m4.726s
sys     0m0.649s
```
