### ISSUE TITLE
I want to modified grafana smtp config but I CAN NOT FIND grafana,ini

### ISSUE THREAD

**Issue by seanlin1326** [coreos/kube-prometheus#562]
I want to add more user in grafana by send email
But I found some error
<img width="762" alt="smtp" src="https://user-images.githubusercontent.com/58818014/83963626-1234ab80-a8da-11ea-8753-78d4dee7d326.PNG">

I want to find grafana.ini to modified this
<img width="518" alt="smtp2" src="https://user-images.githubusercontent.com/58818014/83963683-68095380-a8da-11ea-8047-1736020c0927.PNG">
but my eye is bad
so I can not find grafana.ini in kube-prometheus
how to find  grafana.ini

**Comment by olegmayko** [comment]
The project itself doesn't contain static grafana.ini, you need to customise it  as shown in [this readme](https://github.com/brancz/kubernetes-grafana#config-customization)

**Comment by songrijie** [comment]
Alternative to what @olegmayko said.

Since [grafana can be configured with env variables](https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables),  you may create a simple libsonnet like this.  Do not forget to include this libsonnet in entrypoint mixin.  

```
local k = import 'ksonnet/ksonnet.beta.4/k.libsonnet';
local env = k.apps.v1.deployment.mixin.spec.template.spec.containersType.envType;

{
    _config+:: {
        grafana+: {
            env+: [
                // SMTP
                env.new('GF_SMTP_ENABLED', 'true' ),
                env.new('GF_SMTP_FROM_ADDRESS', 'system@example.com'),
                env.new('GF_SMTP_HOST','smtp.example.com:465'),
                env.new('GF_SMTP_USER','system@example.com'),
                env.new('GF_SMTP_PASSWORD','example'),

            ],
        },
    },
}
```

This idea comes from [brancz/kubernetes-grafana](https://github.com/brancz/kubernetes-grafana/blob/release-0.1/grafana/grafana.libsonnet#L214)
